version: 0.1.{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1

image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
clone_folder: c:\projects\unwind-mc
shallow_clone: true
clone_depth: 5
matrix:
  fast_finish: false

platform: 
  - Any CPU
configuration:
  - Debug
  - Release
build:
  project: src\UnwindMC.sln
  parallel: true
  verbosity: normal
before_build:
  - appveyor-retry nuget restore src\UnwindMC.sln
